# Generated by Django 3.1.4 on 2020-12-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_auto_20201214_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='contry',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_app.country'),
        ),
    ]
