# Generated by Django 3.1.4 on 2020-12-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0003_auto_20201214_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.RemoveField(
            model_name='film',
            name='available_in_countries',
        ),
        migrations.AddField(
            model_name='film',
            name='available_in_countries',
            field=models.ManyToManyField(related_name='film_aviaible_country', to='film_app.Country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_country_creator', to='film_app.country'),
        ),
    ]
